export const locations = [
  {
    id: 1,
    region: "Ashanti",
    city: "Kumasi",
    hotels: [
      { name: "Golden Tulip Kumasi City", address: "Nhyiaeso" },
      { name: "Four Villages Inn", address: "Adum" },
      { name: "Royal Lamerta Hotel", address: "Ahodwo" },
      { name: "True Vine Hotel", address: "Ahodwo" },
      { name: "Noda Hotel", address: "Fumesua" },
    ],
  },
  {
    id: 2,
    region: "Brong Ahafo",
    city: "Sunyani",
    hotels: [
      { name: "Eusbett Hotel", address: "Sunyani" },
      { name: "Tyco City Hotel", address: "Sunyani" },
      { name: "Hotel de Jet", address: "Sunyani" },
      { name: "Peacock Hotel", address: "Sunyani" },
      { name: "Ridge Hotel", address: "Sunyani" },
    ],
  },
  {
    id: 3,
    region: "Central",
    city: "Cape Coast",
    hotels: [
      { name: "Ridge Royal Hotel", address: "Cape Coast" },
      { name: "Oasis Beach Resort", address: "Cape Coast" },
      { name: "Coconut Grove Bridge House", address: "Elmina" },
      { name: "Aho Fie Hotel", address: "Cape Coast" },
      { name: "Atlantic Hotel", address: "Cape Coast" },
    ],
  },
  {
    id: 4,
    region: "Greater Accra",
    city: "Accra",
    hotels: [
      { name: "Kempinski Hotel Gold Coast City", address: "Accra" },
      { name: "Labadi Beach Hotel", address: "Labadi" },
      { name: "Movenpick Ambassador Hotel", address: "Accra" },
      { name: "Accra City Hotel", address: "Accra" },
      { name: "La Palm Royal Beach Hotel", address: "Labadi" },
    ],
  },
  {
    id: 5,
    region: "Western",
    city: "Takoradi",
    hotels: [
      { name: "Raybow International Hotel", address: "Takoradi" },
      { name: "Takoradi Beach Hotel", address: "Beach Road" },
      { name: "Animens Hotel", address: "Sekondi" },
      { name: "Best Western Plus Atlantic Hotel", address: "Takoradi" },
      { name: "Windy Lodge", address: "Takoradi" },
    ],
  },
  {
    id: 6,
    region: "Northern",
    city: "Tamale",
    hotels: [
      { name: "Radach Lodge", address: "Tamale" },
      { name: "Gariba Lodge", address: "Tamale" },
      { name: "Mariam Hotel", address: "Tamale" },
      { name: "Modern City Hotel", address: "Tamale" },
      { name: "TICCS Guest House", address: "Tamale" },
    ],
  },
  {
    id: 7,
    region: "Eastern",
    city: "Koforidua",
    hotels: [
      { name: "New Crystal Hotel", address: "Koforidua" },
      { name: "Mika Lodge Hotel", address: "Koforidua" },
      { name: "Royal Castle Hotel", address: "Koforidua" },
      { name: "Jenyns Hotel", address: "Koforidua" },
      { name: "Eastern Hotel", address: "Koforidua" },
    ],
  },
  {
    id: 8,
    region: "Volta",
    city: "Ho",
    hotels: [
      { name: "Val View Hotel", address: "Ho" },
      { name: "Tino Hotel", address: "Ho" },
      { name: "De Wanta Hotel", address: "Ho" },
      { name: "Mystical Hills Hotel", address: "Ho" },
      { name: "Hill View Hotel", address: "Ho" },
    ],
  },
  {
    id: 9,
    region: "Upper East",
    city: "Bolgatanga",
    hotels: [
      { name: "Bolga Inn Lodge", address: "Bolgatanga" },
      { name: "Soe Pastoral Centre", address: "Bolgatanga" },
      { name: "Catholic Cathedral Guest House", address: "Bolgatanga" },
      { name: "Zuarungu Lodge", address: "Bolgatanga" },
      { name: "Golden Tulip Bolgatanga", address: "Bolgatanga" },
    ],
  },
  {
    id: 10,
    region: "Upper West",
    city: "Wa",
    hotels: [
      { name: "Hi-Lite Hotel", address: "Wa" },
      { name: "St. Francis Guest House", address: "Wa" },
      { name: "Black Star Hotel", address: "Wa" },
      { name: "Royal Hotel", address: "Wa" },
      { name: "New Africa Hotel", address: "Wa" },
    ],
  },
  {
    id: 11,
    region: "Bono East",
    city: "Techiman",
    hotels: [
      { name: "Techiman Sun Hotel", address: "Techiman" },
      { name: "Royal Castle Hotel", address: "Techiman" },
      { name: "De Morn Hotel", address: "Techiman" },
      { name: "Peace Hotel", address: "Techiman" },
      { name: "Liberty Hotel", address: "Techiman" },
    ],
  },
  {
    id: 12,
    region: "Ahafo",
    city: "Goaso",
    hotels: [
      { name: "De Milan Hotel", address: "Goaso" },
      { name: "Ahafo Inn", address: "Goaso" },
      { name: "Royal Court Hotel", address: "Goaso" },
      { name: "Goaso Sun Hotel", address: "Goaso" },
      { name: "Peace Lodge", address: "Goaso" },
    ],
  },
  {
    id: 13,
    region: "North East",
    city: "Nalerigu",
    hotels: [
      { name: "North East Inn", address: "Nalerigu" },
      { name: "Gambaga Lodge", address: "Nalerigu" },
      { name: "Royal Guest House", address: "Nalerigu" },
      { name: "Nalerigu Sun Hotel", address: "Nalerigu" },
      { name: "Community Guest House", address: "Nalerigu" },
    ],
  },
  {
    id: 14,
    region: "Savannah",
    city: "Damongo",
    hotels: [
      { name: "Damongo Inn", address: "Damongo" },
      { name: "Savanna Lodge", address: "Damongo" },
      { name: "Mole Motel", address: "Damongo" },
      { name: "Royal Savannah Hotel", address: "Damongo" },
      { name: "Golden Guest House", address: "Damongo" },
    ],
  },
  {
    id: 15,
    region: "Oti",
    city: "Dambai",
    hotels: [
      { name: "Oti Lodge", address: "Dambai" },
      { name: "Volta River Hotel", address: "Dambai" },
      { name: "Dambai Inn", address: "Dambai" },
      { name: "Royal Oti Hotel", address: "Dambai" },
      { name: "Peace Guest House", address: "Dambai" },
    ],
  },
  {
    id: 16,
    region: "Western North",
    city: "Sefwi Wiawso",
    hotels: [
      { name: "Sefwi Inn", address: "Sefwi Wiawso" },
      { name: "Western North Lodge", address: "Sefwi Wiawso" },
      { name: "Royal Gold Hotel", address: "Sefwi Wiawso" },
      { name: "Green Forest Hotel", address: "Sefwi Wiawso" },
      { name: "Community Lodge", address: "Sefwi Wiawso" },
    ],
  },
];
